export const books = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: 1960,
    genre: "Fiction",
    rating: 4.5,
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    year: 1949,
    genre: "Science Fiction",
    rating: 4.3,
  },
  {
    id: 3,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    genre: "Romance",
    rating: 4.7,
  },
  {
    id: 4,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    year: 1925,
    genre: "Fiction",
    rating: 4.2,
  },
  {
    id: 5,
    title: "To the Lighthouse",
    author: "Virginia Woolf",
    year: 1927,
    genre: "Fiction",
    rating: 4.1,
  },
  {
    id: 6,
    title: "Moby-Dick",
    author: "Herman Melville",
    year: 1851,
    genre: "Adventure",
    rating: 4.4,
  },
  {
    id: 7,
    title: "Jane Eyre",
    author: "Charlotte Bronte",
    year: 1847,
    genre: "Gothic",
    rating: 4.6,
  },
  {
    id: 8,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    year: 1954,
    genre: "Fantasy",
    rating: 4.8,
  },
  {
    id: 9,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    year: 1951,
    genre: "Fiction",
    rating: 4.0,
  },
  {
    id: 10,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    year: 1866,
    genre: "Psychological Fiction",
    rating: 4.5,
  },
  {
    id: 11,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    year: 1937,
    genre: "Fantasy",
    rating: 4.4,
  },
  {
    id: 12,
    title: "War and Peace",
    author: "Leo Tolstoy",
    year: 1869,
    genre: "Historical Fiction",
    rating: 4.7,
  },
  {
    id: 13,
    title: "Brave New World",
    author: "Aldous Huxley",
    year: 1932,
    genre: "Science Fiction",
    rating: 4.2,
  },
  {
    id: 14,
    title: "The Odyssey",
    author: "Homer",
    year: "8th BCE",
    genre: "Epic Poetry",
    rating: 4.6,
  },
  {
    id: 15,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    year: 1890,
    genre: "Gothic Fiction",
    rating: 4.3,
  },
  {
    id: 16,
    title: "Frankenstein",
    author: "Mary Shelley",
    year: 1818,
    genre: "Gothic Fiction",
    rating: 4.4,
  },
  {
    id: 17,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    year: 1605,
    genre: "Satire",
    rating: 4.7,
  },
];
