export const movies = [
  {
    title: "The Shawshank Redemption",
    director: "Frank Darabont",
    year: 1994,
    genre: "Drama",
    rating: 9.3,
  },
  {
    title: "The Godfather",
    director: "Francis Ford Coppola",
    year: 1972,
    genre: "Crime, Drama",
    rating: 9.2,
  },
  {
    title: "The Dark Knight",
    director: "Christopher Nolan",
    year: 2008,
    genre: "Action, Crime, Drama",
    rating: 9.0,
  },
  {
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    year: 1994,
    genre: "Crime, Drama",
    rating: 8.9,
  },
  {
    title: "Fight Club",
    director: "David Fincher",
    year: 1999,
    genre: "Drama",
    rating: 8.8,
  },
  {
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    year: 1994,
    genre: "Drama, Romance",
    rating: 8.8,
  },
  {
    title: "The Matrix",
    director: "Lana Wachowski, Lilly Wachowski",
    year: 1999,
    genre: "Action, Sci-Fi",
    rating: 8.7,
  },
  {
    title: "Goodfellas",
    director: "Martin Scorsese",
    year: 1990,
    genre: "Biography, Crime, Drama",
    rating: 8.7,
  },
  {
    title: "Seven",
    director: "David Fincher",
    year: 1995,
    genre: "Crime, Drama, Mystery",
    rating: 8.6,
  },
  {
    title: "Gone with the Wind",
    director: "Victor Fleming",
    year: 1939,
    genre: "Drama, History, Romance",
    rating: 8.1,
  },
  {
    title: "The Revenant",
    director: "Alejandro González Iñárritu",
    year: 2015,
    genre: "Action, Adventure, Drama",
    rating: 8.0,
  },
  {
    title: "La La Land",
    director: "Damien Chazelle",
    year: 2016,
    genre: "Comedy, Drama, Music",
    rating: 8.0,
  },
];
