export const recipes = [
  { id: 1, name: "Spaghetti Carbonara", creator: "John Smith" },
  { id: 2, name: "Chicken Parmesan", creator: "Emily Johnson" },
  { id: 3, name: "Homemade Pizza", creator: "Michael Davis" },
  { id: 4, name: "Chocolate Chip Cookies", creator: "Sarah Thompson" },
  { id: 5, name: "Beef Tacos", creator: "David Rodriguez" },
  { id: 6, name: "Vegetable Stir-Fry", creator: "Jennifer Lee" },
  { id: 7, name: "Blueberry Pancakes", creator: "Alexis Wilson" },
  { id: 8, name: "Grilled Salmon", creator: "Daniel Clark" },
  { id: 9, name: "Creamy Mushroom Soup", creator: "Olivia Moore" },
  { id: 10, name: "Banana Bread", creator: "Matthew Turner" },
  { id: 11, name: "Caesar Salad", creator: "Sophia Adams" },
  { id: 12, name: "Chicken Curry", creator: "James Carter" },
  { id: 13, name: "Apple Pie", creator: "Natalie Mitchell" },
  { id: 14, name: "Guacamole", creator: "Ethan Taylor" },
  { id: 15, name: "Roasted Chicken", creator: "Ava Martinez" },
  { id: 16, name: "Cheeseburger", creator: "Benjamin Brown" },
  { id: 17, name: "Pasta Primavera", creator: "Victoria Hall" },
  { id: 18, name: "Mango Salsa", creator: "Jacob Hernandez" },
  { id: 19, name: "Ratatouille", creator: "Grace Phillips" },
  { id: 20, name: "Greek Salad", creator: "Christopher Turner" },
  { id: 21, name: "Beef Stew", creator: "Amelia Adams" },
  { id: 22, name: "Crispy Fried Chicken", creator: "William Wilson" },
  { id: 23, name: "Tomato Soup", creator: "Sophia Martinez" },
  { id: 24, name: "Omelette", creator: "Elijah Brown" },
  { id: 25, name: "Honey Glazed Salmon", creator: "Charlotte Clark" },
  { id: 26, name: "Pancakes", creator: "Henry Davis" },
  { id: 27, name: "Garden Salad", creator: "Chloe Thompson" },
  { id: 28, name: "Beef and Broccoli Stir-Fry", creator: "Noah Phillips" },
  { id: 29, name: "Vanilla Cupcakes", creator: "Emily Wilson" },
  { id: 30, name: "Baked Ziti", creator: "Alexander Carter" },
  { id: 31, name: "Lemon Bars", creator: "Sofia Hernandez" },
  { id: 32, name: "Chicken Noodle Soup", creator: "Liam Turner" },
  { id: 33, name: "Sushi Rolls", creator: "Grace Davis" },
  { id: 34, name: "Chocolate Brownies", creator: "Oliver Martinez" },
  { id: 35, name: "Tiramisu", creator: "Zoe Thompson" },
  { id: 36, name: "Beef Enchiladas", creator: "Eva Adams" },
  { id: 37, name: "Potato Salad", creator: "Lucas Clark" },
  { id: 38, name: "Shrimp Scampi", creator: "Mia Phillips" },
  { id: 39, name: "Butter Chicken", creator: "Jackson Wilson" },
  { id: 40, name: "Pumpkin Soup", creator: "Sophie Turner" },
  { id: 41, name: "Chili Con Carne", creator: "William Hernandez" },
  { id: 42, name: "Apple Crisp", creator: "Emily Martinez" },
  { id: 43, name: "Stuffed Bell Peppers", creator: "James Brown" },
  { id: 44, name: "Cobb Salad", creator: "Aria Adams" },
  { id: 45, name: "Garlic Shrimp Pasta", creator: "Ryan Wilson" },
  { id: 46, name: "Peanut Butter Cookies", creator: "Grace Thompson" },
  { id: 47, name: "Beef Stir-Fry", creator: "Lucy Davis" },
  { id: 48, name: "Strawberry Shortcake", creator: "Benjamin Clark" },
  { id: 49, name: "Fish Tacos", creator: "Scarlett Hernandez" },
  { id: 50, name: "Spinach and Feta Stuffed Chicken", creator: "Leo Turner" },
];
