export const products = [
  {
    id: 1,
    name: "Product 1",
    price: 9.99,
    category: "Electronics",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 2,
    name: "Product 2",
    price: 19.99,
    category: "Home",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 3,
    name: "Product 3",
    price: 14.99,
    category: "Books",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 4,
    name: "Product 4",
    price: 49.99,
    category: "Electronics",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 5,
    name: "Product 5",
    price: 9.99,
    category: "Beauty",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 6,
    name: "Product 6",
    price: 29.99,
    category: "Electronics",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 7,
    name: "Product 7",
    price: 12.99,
    category: "Home",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 8,
    name: "Product 8",
    price: 24.99,
    category: "Books",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 9,
    name: "Product 9",
    price: 7.99,
    category: "Beauty",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 10,
    name: "Product 10",
    price: 39.99,
    category: "Electronics",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 11,
    name: "Product 11",
    price: 17.99,
    category: "Home",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 12,
    name: "Product 12",
    price: 11.99,
    category: "Books",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 13,
    name: "Product 13",
    price: 8.99,
    category: "Beauty",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 14,
    name: "Product 14",
    price: 34.99,
    category: "Electronics",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 15,
    name: "Product 15",
    price: 22.99,
    category: "Home",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 16,
    name: "Product 16",
    price: 15.99,
    category: "Books",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 17,
    name: "Product 17",
    price: 6.99,
    category: "Beauty",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 18,
    name: "Product 18",
    price: 27.99,
    category: "Electronics",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 19,
    name: "Product 19",
    price: 16.99,
    category: "Home",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 20,
    name: "Product 20",
    price: 10.99,
    category: "Books",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];
